version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
      - ./config/init-mongo:/docker-entrypoint-initdb.d/
    networks:
      - mongo_network

volumes:
  mongodb_data:
    driver: local

networks:
  mongo_network:
    driver: bridge

